import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased scroll-smooth">
      {/* Applying inter.className directly to the body sets it as the default */}
      <body
        className={`${inter.className} min-h-screen flex flex-col bg-fixed bg-linear-to-br from-[#fcfbf9] via-[#f0ede8] to-[#e2ded5] `}
      >
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
